language: python
sudo: false
branches:
  except:
    - gh-pages

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-ansible19
    - python: 2.7
      env: TOXENV=py27-ansible20
    - python: 2.7
      env: TOXENV=py27-ansible21

install:
  - pip install tox

before_script:
  - mkdir -p log

script:
  - tox

after_success:
  - pylint ansible_toolkit
  - pip install coveralls
  - coveralls
